# Generated by Django 4.1.6 on 2023-04-12 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'country code is not required')])),
                ('pinCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('password', models.CharField(max_length=30)),
                ('prfImg', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Fimg', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('PImage', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
