# Generated by Django 4.1.6 on 2023-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_register_alter_order_phone_alter_upload_phone'),
        ('farmregister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
