# Generated by Django 4.1.6 on 2023-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='register',
            name='Fimg',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='register',
            name='PImage',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='register',
            name='prfImg',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
