# Generated by Django 4.1.6 on 2023-04-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_orders_order_rename_name_register_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='fname',
        ),
    ]
