# Generated by Django 4.1.6 on 2023-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_name_register_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='name',
        ),
    ]
