# Generated by Django 4.1.6 on 2023-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmregister', '0001_initial'),
        ('Home', '0004_rename_fname_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmregister.register'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmregister.register'),
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
