# Generated by Django 4.1.6 on 2023-04-12 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_order_phone_alter_upload_phone_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'country code is not required')])),
                ('pinCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('password', models.CharField(max_length=30)),
                ('prfImg', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Fimg', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('PImage', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Home.register'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.register'),
        ),
    ]
